### ISSUE TITLE
Create User Interface

### ISSUE THREAD

**Issue by Elementator** [amosproj/amos2023ws04-pipeline-manager#4]
## User story
1. As a User
2. I need a GUI
3. So that work with the CNP

## Subtasks

- [ ] Upload data
- [ ] Select suitable data pipeline
- [ ] Search and retrieve data and their relevant informations
- [ ] Check and control status of CNP 

## Definition of done (DoD)

- [ ] Able to upload 1 file
- [ ] Able to upload multiple files
- [ ] Can select 1 data pipeline
- [ ] Can select from multiple data pipeline
- [ ] Search database via SQL for specific metadata
- [ ] Retrive relevant raw data 
- [ ] Data downloadable/know where it is stored
- [ ] Able to download 1 file
- [ ] Able to download multiple files
- [ ] Able to download all files
- [ ] See upload date of retrieved data
- [ ] See size of retrieved data
- [ ] See file type of retrieved data

**Comment by Elementator** [comment]
## Subtasks

- [ ] Test 1
- [ ] Test2

**Comment by krutarth4** [comment]
@Elementator do we still need this issue, I don't think so. Hence I am closing it for now.
